spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-emotion-feedback.czyqweykwib4.ap-northeast-2.rds.amazonaws.com:5432/emotionFeedback
    username: jach1206
    password: iuoo856963

  web:
    websocket:
      enabled: true  # WebSocket 기능을 활성화합니다.

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #      show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt:
  secret: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff


